name: Moving Average Calculator

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10.14
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.14

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with pylint
      run: |
        pylint moving_average_calculator/*.py tests/*.py

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover
        coverage report -m
        
    - name: Generate coverage badge
      run: |
        rm -f ./media/coverage.svg
        coverage-badge -o ./media/coverage.svg

    - name: Checkout master
      run: |
        git fetch
        git checkout master

    - name: Commit coverage badge
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./media/coverage.svg
        if ! git diff --quiet; then
          git commit -m "Update coverage badge"
          git push
        fi