name: Moving Average Calculator

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10.14
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.14

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with pylint
      run: |
        pylint moving_average_calculator/*.py tests/*.py

    - name: Test with unittest
      run: |
        python -m unittest discover

    - name: Test coverage with unittest
      run: |
        coverage run -m unittest discover
        coverage report -m